# for paperclip-data
app_key: YOUR_APP_KEY
app_secret: YOUR_APP_SECRET
access_token: YOUR_ACCESS_TOKEN
access_token_secret: YOUR_ACCESS_TOKEN_SECRET
user_id: YOUR_USER_ID
access_type: YOUR_ACCESS_TYPE
